anamneza(,[povisena_telesna_tempetatura]).
pregled(,[stitasta_zlezda_deformisane_konture]).
anamneza(rada,[povisena_telesna_tempetatura]).
pregled(rada,[stitasta_zlezda_deformisane_konture]).
anamneza(mika,[genetski_faktor]).
pregled(mika,[stitasta_zlezda_deformisane_konture]).
anamneza(ziza,[modra_noga]).
pregled(ziza,[arterijski_protok_se_registruje]).
anamneza(fdfsfsf,[modra_noga]).
pregled(fdfsfsf,[arterijski_protok_se_registruje]).
anamneza(dsda,[modra_noga]).
pregled(dsda,[arterijski_protok_se_registruje]).
