anamneza(rada,[bolno_mokrenje_krvi]).
pregled(rada,[bubreg_je_uvecan]).
anamneza(masa,[bezbolno_mokrenje_krvi]).
pregled(masa,[bubreg_je_uvecan]).
anamneza(mara,[bezbolno_mokrenje_krvi]).
pregled(mara,[bubreg_je_uvecan,krvni_sudovi_na_rubu_cvora]).
anamneza(maca,[bezbolno_mokrenje_krvi]).
pregled(maca,[bubreg_je_uvecan,krvni_sudovi_u_centru_cvora]).
anamneza(macaaaa,[bezbolno_mokrenje_krvi]).
pregled(macaaaa,[bubreg_je_uvecan,krvni_sudovi_u_centru_cvora,cvor_u_bubregu]).
anamneza(macaaa,[bezbolno_mokrenje_krvi]).
pregled(macaaa,[bubreg_je_uvecan,krvni_sudovi_u_centru_cvora,cvor_u_bubregu_i_delom_van_bubrega]).
